language: go

go:
    - tip

before_install:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls

script:
    - go test -covermode=count -coverprofile=coverage.out
    :w
    
notifications:
    email: false
