language: go

go:
    - tip

before_install:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls

script:
    - go test -covermode=count -coverprofile=coverage.out
    - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN

notifications:
    email: false
